---
galaxy_info:
  role_name: security_stack
  author: BOURGUET-LAFFELY-CUEFF
  description: Déploiement idempotent de la stack sécurité transverse via Docker Compose
  min_ansible_version: "2.14"
dependencies:
  - role: docker
  - role: git
  - role: traefik
