---
galaxy_info:
  role_name: wazuh
  author: BOURGUET-LAFFELY-CUEFF
  description: Déploiement idempotent du SIEM Wazuh via Docker Compose
  min_ansible_version: "2.14"
dependencies:
  - role: docker
  - role: git
