name: Trivy Scan (Docker Compose + Images)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '44 3 * * 3'  # Tous les mercredis à 3h44

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  trivy-scan:
    name: Scan Docker Compose and Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name:  Scan all files         
        run: | 
          trivy fs --scanners vuln,secret,misconfig .


      - name: Scan Docker Compose Configuration
        run: |
          trivy config --file-patterns "dockerfile:Dockerfile" compose.yml


      - name: Scan Docker Compose Applicatif Configuration
        run: |
          # Scanner tous les fichiers YAML du répertoire
          trivy config --format table .

      - name: Scan Security Docker Compose Configuration
        run: |
          # Scanner tous les fichiers YAML du répertoire
          trivy config security/docker-compose.security.yml

      - name: Scan Images in Applicatif Docker Compose
        run: |
          trivy image --compliance docker-cis-1.6.0 node:24
          trivy image --compliance docker-cis-1.6.0 postgres
          trivy image -compliance docker-cis-1.6.0 nginx:alpine

      - name: Scan Images in Security Docker Compose
        run: |
          trivy image --compliance docker-cis-1.6.0 falco-no-driver:latest
          trivy image --compliance docker-cis-1.6.0 suricata:latest
          trivy image --compliance docker-cis-1.6.0 wazuh-manager:4.7.3
          trivy image --compliance docker-cis-1.6.0 wazuh-indexer:4.7.3
          trivy image --compliance docker-cis-1.6.0 wazuh-dashboard:4.7.3
          trivy image --compliance docker-cis-1.6.0 shuffle-frontend:latest
          trivy image --compliance docker-cis-1.6.0 shuffle-backend:latest
          trivy image --compliance docker-cis-1.6.0 http-request-action:latest

  


      # - name: Build Docker Image (if needed)
      #   run: |
      #     docker compose -f compose.yml build

      # - name: Scan Built Images with Trivy
      #   uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
      #   with:
      #     image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
      #     format: 'template'
      #     template: '@/contrib/sarif.tpl'
      #     output: 'trivy-results.sarif'
      #     severity: 'CRITICAL,HIGH'

      # - name: Upload Trivy SARIF Results
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: 'trivy-results.sarif'
